### ISSUE TITLE
Python 2.7 travis flake8 problem.

### ISSUE THREAD

**Issue by warmspringwinds** [cs231n/cs231n.github.io#29]
Every time the travis checks are ran after my commits, I have the follwing mistake and I saw a lot of pull requests having the same:

Flake8 test *

+flake8 --exit-zero '--exclude=test_*,six.py' skimage doc/examples viewer_examples

Traceback (most recent call last):

File "/home/travis/venv/bin/flake8", line 7, in <module>

from flake8.main import main

File "/home/travis/venv/local/lib/python2.7/site-packages/flake8/main.py", line 5, in <module>

import setuptools

File "/home/travis/venv/local/lib/python2.7/site-packages/setuptools/init.py", line 11, in <module>

from setuptools.extension import Extension

File "/home/travis/venv/local/lib/python2.7/site-packages/setuptools/extension.py", line 8, in <module>

from .dist import _get_unpatched

File "/home/travis/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 21, in <module>

packaging = pkg_resources.packaging

AttributeError: 'module' object has no attribute 'packaging'`

Is there a way to avoid it?

Thank you

**Comment by warmspringwinds** [comment]
sorry, wrong repository :)
